### ISSUE TITLE
子应用怎么加载到父应用对应位置处

### ISSUE THREAD

**Issue by Jarryxin** [polyglot-microfrontends/account-settings#10]
![image](https://user-images.githubusercontent.com/21277570/118228249-708be600-b4bc-11eb-9abc-f2c860268513.png)
红色箭头代表的是主+子应用，蓝色箭头代表想把子应用渲染到主应用的位置

**Comment by joeldenning** [comment]
Applications do not have hierarchy - they are all siblings.

If you want hierarchy, consider [single-spa parcels](https://zh-hans.single-spa.js.org/docs/parcels-overview)
